config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/auth/failure', to: 'users/omniauthcallbacks#failure'
  get '/contacts', to: 'contacts#index', as: 'contacts'
  post '/contacts/pull', to: 'contacts#pull', as: 'pull_contacts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :omniauthable,
    omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    User.find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/user/not_logged.rb
# Null Object Pattern
class User::NotLogged
  attr_reader :name, :email, :image

  def initialize
    @name = nil
    @email = nil
    @image = nil
  end

  def self.persisted?
    false
  end

  def self.errors
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

  def after_sign_in_path_for(resource)
    contacts_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts = Contact.paginate(:page => params[:page], :per_page => Rails.configuration.per_page)
  end

  def pull
    ContactsJob.perform_async(current_user.id, Rails.configuration.page_size)
    respond_to do |format|
      format.js {}
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = UserService.create(request.env['omniauth.auth'])
    @user.persisted? ? success : failure
  end

  def failure
    redirect_to root_path, alert: I18n.t('errors.access_not_granted')
  end

  private

  def success
    flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
    sign_in_and_redirect @user, event: :authentication
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/index.html.erb
<div class="my-4">
  <%= link_to 'Pull contacts', pull_contacts_path, class: 'btn btn-outline-primary',
    data: { 'js-spinner': true }, method: :post, remote: true %>
</div>

<div class="mx-auto my-4 loader"></div>

<% if @contacts && @contacts.count > 0 %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @contacts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<% end %>

app/views/layouts/_messages.html.erb
<div class="mx-auto messages">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible fade show alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h5 class="my-0 mr-md-auto font-weight-normal">My Google Contacts</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to 'Contacts', contacts_path, class: 'p-2 text-dark', role: 'button' %>
  </nav>
  <%= render 'layouts/navigation_links' %>
</div>

app/views/layouts/_navigation_links.html.erb
<% if current_user %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary', role: 'button' %>
<% else %>
  <%= link_to 'Sign in with Google', user_google_oauth2_omniauth_authorize_path, class: 'btn btn-outline-primary', role: 'button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Google Contacts" %>">
    <title><%= content_for?(:title) ? yield(:title) : "Google Contacts" %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
   <section>
     <%= render 'layouts/messages' %>
     <div class="container">
       <%= yield %>
     </div>
   </section>
  </body>
</html>